- .gitignore
> Added .gitignore with relevant python ignores

- src/sensors/Cleanser.py
- tests/test_Cleanser.py
added the cleanser file to sensors and tested all possibilities in the tests file. 
this cleanser can only remove outliers within different standard deviations. 
user selects sensor and how many standard deviation ranges to include.
> Adding cleanser functionalities

- src/sensors/Cleanser.py
- tests/test_Cleanser.py
> Cleanser Class needs to cleanse the values that are stored in the sensor object values.

- src/flaskr/templates/main/home.html
These form guidlines include:
channel_id
field_id
start_date
Time_increment
As well as using the base.html jinja template and including a submit button
> Birdbh/issue134 -> Development of main.html to match the form guidlines needed for main.py

- src/DataGeneration.py
- src/sensors/sensor.py
- tests/test_sensor.py
Fixes #143 -> As seen above and updated the tests for both sensor and DataGeneration. @Jcp149 after this is approved or rejected you can update the cleanser class but with this change prediction and cleanser should be better set up now.
> Birdbh/issue143 -> Addition of Functionality for sensors to get and set the values of the date range and values

- src/sensors/Cleanser.py
- tests/test_Cleanser.py
fixed issue making the value set not match the length of the date set by skipping the pop step and just setting values removed to the previous data value
added remove min and max and added a test that covers both!
closes #153
> fixed cleanser and added remove min and max

- .flaskenv
- src/flaskr/__init__.py
- src/flaskr/auth.py
- src/flaskr/routing.py
- src/flaskr/templates/base.html
This addition allows us to get proper routing and implement passing of variables and classes between different HTML pages
Completes issue #155
> Add routing issue155

- PythonRequirements.bat
> Create PythonRequirements.bat per #124

- src/flaskr/templates/main/home.html
> Issue#107: Develop main.html & login.html pages. (HTML Weekly Goal)

- src/sensors/Cleanser.py
- src/sensors/DecoratorPattern.py
- src/sensors/Prediction.py
- src/sensors/sensor.py
- tests/test_DecoratorPattern.py
- tests/test_Prediction.py
> Implement Decorator Pattern for sensor, cleanser, and prediction -> including: addition of classes, modification of necessary tests.

- README.md
Update README to better format the user requirments and explain briefly how to run the project.
> Update README to better format the user requirments and explain briefly how to run the project.

- src/Chart.py
- tests/test_Chart.py
Added the chart class which will intake a sensor and has get values and get labels. values simply returns the sensor values, but labels forces the date time into a string and returns a list of strings to be able ot label the chart. overall just makes making charts easier. 
closes #198
> added chart class and full test suite

- src/flaskr/static/style.css
Fixes #189 
Some additional changes to the style.css format.
> Link and Update style.css File with HTML Files

- src/Chart.py
- src/flaskr/__init__.py
- src/flaskr/home.py
- src/flaskr/routing.py
- src/flaskr/templates/base.html
- src/flaskr/templates/main/home.html
- tests/test_Chart.py
- tests/test_home.py
home,py updated and working now, some updates needs for future
test class only for connection so far
> Updating home.py and adding test class for it

- src/flaskr/templates/auth/login.html
- src/flaskr/templates/main/home.html
I fixed some formatting issues. I am working on changing overall formatting on a separate issue.
> Issue190: Run Tests to check HTML functionality via Flask App.

- src/flaskr/home.py
> Bug needs to be fixed when a non-premium user tries to select data from Thinkspeak API.

- src/flaskr/home.py
- src/flaskr/routing.py
> Fix bug for non-public fields and creates flash message that cleanse must be selected in order to predict data.

- src/flaskr/static/style.css
- src/flaskr/templates/base.html
- src/flaskr/templates/main/home.html
> Issue226: Add in Alarm Alert Functionality to home.html

- src/flaskr/templates/main/home.html
Added downloads for premium users. Adds a download button which downloads as a PNG
per issue #38
> Added downloading per issue 38

- src/flaskr/templates/main/home.html
> Update HTML formatting for home.html
